def print_usage():
    print("Usage: python typist.py [command] [options]")
    print("Commands:")
    print("  file (f): Select a file to work on.")
    print("  change (c): Apply a change to the selected file.")
    print("  test_cmd (tc): Set the test command.")
    print("  run_test (run): Run the test command.")
    print("  instructions (i): Set custom instructions for the change.")
    print("  retry (r): Retry the last change.")
    print("  approve (a): Approve the changes.")
    print("  status (st): Display the current status.")
    print("  format (fmt): Set the formatter command.")
    print("  diff_cmd (diff): Set the diff command.")
